language: python
sudo: required
python:
  - "3.6"
install:
  - sudo pip install -r requirements.txt
  - sudo pip install nose
  - sudo pip install coveralls
script:
  - sudo nosetests --with-coverage
after_success:
  - coveralls

